
server:
  port: 6666


spring:
  application:
    name: redisson-task
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      # 数据库
      database: 4
      # 主机
      host: localhost
      # 端口
      port: 6379
      # 密码
      password: 123456
      # 读超时
      timeout: 5s
      # 连接超时
      connect-timeout: 5s
